version: '3'
services:
  ping-pong-api:
    build: .
    ports:
      - "3000:3000"
    restart: always
    working_dir: /usr/src/app
    command: node index.js
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30